# Generated by Django 4.0.3 on 2022-03-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_dete_of_death_author_date_of_death'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='display_author',
        ),
    ]
