# Generated by Django 4.0.3 on 2022-03-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_author_book_display_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='display_author',
            new_name='author',
        ),
    ]
